name: Terraform New Relic Dashboard Workflow

on:
  # push:
  #   branches:
  #     - main 
  # pull_request:
  #   branches:
  #     - main  
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Terraform Init
        env:
          TF_VAR_id: ${{ secrets.NEWRELIC_ACCOUNT_ID }}
          TF_VAR_api: ${{ secrets.NEWRELIC_API_KEY }}
        run: terraform init

      # - name: Terraform Validate
      #   run: terraform validate

      - name: Terraform Plan
        run: terraform plan 
        env:
          TF_VAR_id: ${{ secrets.NEWRELIC_ACCOUNT_ID }}
          TF_VAR_api: ${{ secrets.NEWRELIC_API_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve 
        env:
          TF_VAR_id: ${{ secrets.NEWRELIC_ACCOUNT_ID }}
          TF_VAR_api: ${{ secrets.NEWRELIC_API_KEY }}

   


      - name: Terraform Destroy Specific Resources
        if: github.event_name == 'workflow_dispatch'
        env:
          TF_VAR_id: ${{ secrets.NEWRELIC_ACCOUNT_ID }}
          TF_VAR_api: ${{ secrets.NEWRELIC_API_KEY }}
        run: terraform destroy -target=module.name.newrelic_one_dashboard.dynamicdashboard -auto-approve




      # - name: Cleanup
      #   run: rm -f tfplan

